### ISSUE TITLE
Option --skip-restructuring not recognized

### ISSUE THREAD

**Issue by andrenarchy** [less/less-plugin-clean-css#11]
The plugin does not recognize the clean-css option `--skip-restructuring`.

**Comment by lukeapage** [comment]
Would you like to make a PR? it should be a simple change to https://github.com/less/less-plugin-clean-css/blob/master/lib/parse-options.js#L8

**Comment by andrenarchy** [comment]
Can you also publish a new release on npm when the PR is merged?

**Comment by lukeapage** [comment]
will publish now.

**Comment by lukeapage** [comment]
done.

**Comment by andrenarchy** [comment]
Thanks for reacting so quickly! :smiley:
