### ISSUE TITLE
Breaks on CSS Function

### ISSUE THREAD

**Issue by Spedwards** [less/less-plugin-clean-css#15]
So I use a fair bit of CSS functions in my CSS, mainly `calc()`, and this plugin breaks it. For example, this is one of my rules:

    width: calc(100% - 2em - 100px);

After it goes through the plugin, it ends up like this:

    width: calc(-2%);

**Comment by seven-phases-max** [comment]
It's not the plugin, but the Less compiler itself. See [`--strict-math` option](http://lesscss.org/usage/#command-line-usage-strict-math) (and https://github.com/less/less.js/issues/974 for more tips).

**Comment by seven-phases-max** [comment]
Closing as not plugin issue (and expected behaviour after all).
