### ISSUE TITLE
Problem with sourcemaps

### ISSUE THREAD

**Issue by tonygustafsson** [less/less-plugin-clean-css#7]
When I use sourcemaps in less, I get Unexpected token error in source-map-consumer.js:20.

**Comment by lukeapage** [comment]
Please can you provide more information?

**Comment by XhmikosR** [comment]
I'm not sure the current code does what it's supposed to...:

```js
            if (sourceMap) {
                var sourceMapURL = sourceMap.getSourceMapURL();
                css += sourceMap.getCSSAppendage();
            }
```

`sourceMapURL` is assigned but never used.

**Comment by rjgotten** [comment]
> I'm not sure the current code does what it's supposed to

It doesn't.

There's a lot of needlessly complicated (and partially incomplete!) manual processing where sourcemap JSON is turned back into objects and `sources` and `sourcesContent` arrays are being manually merged, when all you need to do is wrap the input map into a `SourceMapConsumer` and apply that to the source map generator using `applySourceMap`:

```js
process : function ( css, extra ) {
  var
    options    = this.options,
    sourceMaps = extra.sourceMap,
    inputMap   = sourceMaps && sourceMaps.getExternalSourceMap(),
    output;

  options.processImport = false;

  if ( typeof options.keepSpecialComments === "undefined" ) {
    options.keepSpecialComments = "*";
  }

  if ( typeof options.rebase === "undefined" ) {
    options.rebase = false;
  }

  if ( typeof options.advanced === "undefined" ) {
    options.advanced = false;
  }

  if ( inputMap ) {
    // Strip existing source map URL, or it may end up in sourcesContent.
    css = css.replace( /\/\*\# sourceMappingURL=.*\*\/$/, "" );
  }

  var output = new CleanCSS( options ).minify( css );

  if ( inputMap ) {
    output.sourceMap.applySourceMap(
      new SourceMapConsumer( inputMap ),
      sourceMaps.getOutputFileName() || ""
    );

    sourceMaps.setExternalSourceMap( output.sourceMap.toString());
    output.styles += sourceMaps.getCSSAppendage();
  }

  return output.styles;
}
```

**Comment by XhmikosR** [comment]
@rjgotten: please submit a PR and ping me.

**Comment by Badestrand** [comment]
Any progress? I can't use this plugin as well as it messes with the source map path somehow (`Error: ENOENT: no such file or directory, open '[root-dir]/bundle.css.map'`).
