### ISSUE TITLE
Compressed CSS - space removal breaks some background images in IE8

### ISSUE THREAD

**Issue by c41** [less/less-plugin-clean-css#9]
Hi, 

a) I hope I'm asking this question in the right place - let me know if not.

b) Sorry for raising an issue involving IE8. Yeah I know - ancient, but we have a decent amount of users on it, so trying to sort out a real world issue.

I'm a CodeKit user, which has just removed the 'remove whitespace' option for outputting LESS to CSS because I gather this setting has been deprecated. The problem is, outputting to 'compressed' causes an issue in IE8. here's the problem:

**this background image works in IE 8...**
background:url('/img/bg.png') no-repeat;

**this background image does not work in IE 8 -because when outputted, 'compressed' mode has removed the space before 'no-repeat' causing the image not to load...**
background:url('/img/bg.png')no-repeat;

Is this a bug or is there a way to avoid compressing individual rules? I'm not a hardcore user - have not used Grunt etc. (which is why i love CodeKit)

Any help appreciated,
Pete

**Comment by lukeapage** [comment]
Check out clean css,  which this plugin uses -https://github.com/jakubpawlowicz/clean-css

There is a compatibility option,  you can set that to ie8... If thst doesn't work,  raise a bug with them.

**Comment by c41** [comment]
Thanks for the tip. I'm delighted to say I was able to sidestep the issue by simply re-ordering the background properties in each affected CSS rule.

For anyone coming along later, this is specifically related to using the background property along with  shorthand values.

If you are minifying your CSS, the following will cause problems for you in IE 8 (the space before 'no-repeat' is removed on minification and causes the image to not load):
**.style {background: url('/img/bg.png') no-repeat 100% 100%}**

Rearrange your properties like the following before minification (so the url/img path is last) and all will be fine in IE8:
**.style {background: no-repeat 100% 100% url('/img/bg.png')}**
